"""new fields in user model

Revision ID: 237dd1a21380
Revises: fb5819f8f1a1
Create Date: 2022-07-23 16:37:10.856574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237dd1a21380'
down_revision = 'fb5819f8f1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
