"""followers

Revision ID: 622cba39fb31
Revises: 237dd1a21380
Create Date: 2022-07-31 13:33:24.758341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622cba39fb31'
down_revision = '237dd1a21380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
